// All palettes — CSS variable values keyed by palette id
// Each palette is a complete set of design tokens

export const palettes = {
  // ─── LIGHT PALETTES ───
  taj: {
    id: "taj", name: "Taj", mode: "light",
    description: "Warm alabaster, elegant paper-like",
    swatch: ["#FAF9F6", "#C5A059", "#2B2620"],
    vars: {
      "--background": "#FAF9F6",
      "--surface": "#FFFFFF",
      "--surface-raised": "#FFFFFF",
      "--surface-sunken": "#F3F1EC",
      "--text": "#2B2620",
      "--text-secondary": "#5C554A",
      "--text-muted": "#6B6459",
      "--border": "#E7E2D8",
      "--border-subtle": "#F0ECE4",
      "--accent": "#C5A059",
      "--accent-subtle": "#F5EDD8",
      "--accent-text": "#FFFFFF",
      "--destructive": "#DC2626",
      "--success": "#16A34A",
      "--warning": "#D97706",
    },
  },
  sky: {
    id: "sky", name: "Sky", mode: "light",
    description: "Cool, clean, office bright",
    swatch: ["#F7FAFC", "#2563EB", "#1E293B"],
    vars: {
      "--background": "#F7FAFC",
      "--surface": "#FFFFFF",
      "--surface-raised": "#FFFFFF",
      "--surface-sunken": "#EFF3F8",
      "--text": "#1E293B",
      "--text-secondary": "#475569",
      "--text-muted": "#64748B",
      "--border": "#E2E8F0",
      "--border-subtle": "#F1F5F9",
      "--accent": "#2563EB",
      "--accent-subtle": "#DBEAFE",
      "--accent-text": "#FFFFFF",
      "--destructive": "#DC2626",
      "--success": "#16A34A",
      "--warning": "#D97706",
    },
  },
  mint: {
    id: "mint", name: "Mint", mode: "light",
    description: "Soft green, calm natural",
    swatch: ["#F3FAF6", "#059669", "#1F2A24"],
    vars: {
      "--background": "#F3FAF6",
      "--surface": "#FFFFFF",
      "--surface-raised": "#FFFFFF",
      "--surface-sunken": "#E8F5EE",
      "--text": "#1F2A24",
      "--text-secondary": "#3D5347",
      "--text-muted": "#5C7A6A",
      "--border": "#DBEEE3",
      "--border-subtle": "#EDF7F1",
      "--accent": "#059669",
      "--accent-subtle": "#D1FAE5",
      "--accent-text": "#FFFFFF",
      "--destructive": "#DC2626",
      "--success": "#16A34A",
      "--warning": "#D97706",
    },
  },
  sugam: {
    id: "sugam", name: "Sugam", mode: "light",
    description: "High-contrast, warm, elder-friendly",
    swatch: ["#FFF9F0", "#B45309", "#1A1A1A"],
    vars: {
      "--background": "#FFF9F0",
      "--surface": "#FFFFFF",
      "--surface-raised": "#FFFFFF",
      "--surface-sunken": "#FFF3E0",
      "--text": "#1A1A1A",
      "--text-secondary": "#3D3D3D",
      "--text-muted": "#5C5C5C",
      "--border": "#D4C4A8",
      "--border-subtle": "#E8DCC8",
      "--accent": "#B45309",
      "--accent-subtle": "#FDE68A",
      "--accent-text": "#FFFFFF",
      "--destructive": "#B91C1C",
      "--success": "#15803D",
      "--warning": "#B45309",
    },
  },
  shaant: {
    id: "shaant", name: "Shaant", mode: "light",
    description: "Sepia, warm reading mode",
    swatch: ["#F5EFE4", "#B27A3F", "#2B2016"],
    vars: {
      "--background": "#F5EFE4",
      "--surface": "#FBF7EF",
      "--surface-raised": "#FFFFFF",
      "--surface-sunken": "#EDE5D6",
      "--text": "#2B2016",
      "--text-secondary": "#4A3C2E",
      "--text-muted": "#7A6B57",
      "--border": "#DDD2C0",
      "--border-subtle": "#EAE2D4",
      "--accent": "#B27A3F",
      "--accent-subtle": "#F5E6D0",
      "--accent-text": "#FFFFFF",
      "--destructive": "#B91C1C",
      "--success": "#15803D",
      "--warning": "#B45309",
    },
  },
  "hc-light": {
    id: "hc-light", name: "High Contrast Light", mode: "light",
    description: "Maximum contrast light",
    swatch: ["#FFFFFF", "#000000", "#0050A0"],
    vars: {
      "--background": "#FFFFFF",
      "--surface": "#FFFFFF",
      "--surface-raised": "#F5F5F5",
      "--surface-sunken": "#EEEEEE",
      "--text": "#000000",
      "--text-secondary": "#1A1A1A",
      "--text-muted": "#333333",
      "--border": "#000000",
      "--border-subtle": "#666666",
      "--accent": "#0050A0",
      "--accent-subtle": "#D0E4F7",
      "--accent-text": "#FFFFFF",
      "--destructive": "#B91C1C",
      "--success": "#15803D",
      "--warning": "#B45309",
    },
  },

  // ─── DARK PALETTES ───
  saffron: {
    id: "saffron", name: "Saffron", mode: "dark",
    description: "Signature brand dark with saffron accent",
    swatch: ["#0B0E14", "#F97316", "#F5F5F7"],
    vars: {
      "--background": "#0B0E14",
      "--surface": "#141922",
      "--surface-raised": "#1C2333",
      "--surface-sunken": "#070A0F",
      "--text": "#F5F5F7",
      "--text-secondary": "#C8CDDA",
      "--text-muted": "#A6ADBB",
      "--border": "rgba(255,255,255,0.08)",
      "--border-subtle": "rgba(255,255,255,0.04)",
      "--accent": "#F97316",
      "--accent-subtle": "rgba(249,115,22,0.15)",
      "--accent-text": "#FFFFFF",
      "--destructive": "#EF4444",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
    },
  },
  indigo: {
    id: "indigo", name: "Indigo", mode: "dark",
    description: "Deep indigo, modern pro",
    swatch: ["#0B1020", "#6366F1", "#EEF0FA"],
    vars: {
      "--background": "#0B1020",
      "--surface": "#151B30",
      "--surface-raised": "#1E2545",
      "--surface-sunken": "#070B18",
      "--text": "#EEF0FA",
      "--text-secondary": "#B8BDD0",
      "--text-muted": "#8B92A8",
      "--border": "rgba(255,255,255,0.08)",
      "--border-subtle": "rgba(255,255,255,0.04)",
      "--accent": "#6366F1",
      "--accent-subtle": "rgba(99,102,241,0.15)",
      "--accent-text": "#FFFFFF",
      "--destructive": "#EF4444",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
    },
  },
  emerald: {
    id: "emerald", name: "Emerald", mode: "dark",
    description: "Deep green-charcoal, calm dark",
    swatch: ["#06110E", "#10B981", "#EAF3EF"],
    vars: {
      "--background": "#06110E",
      "--surface": "#0E1A16",
      "--surface-raised": "#152922",
      "--surface-sunken": "#040C09",
      "--text": "#EAF3EF",
      "--text-secondary": "#B0CFC2",
      "--text-muted": "#7FAA98",
      "--border": "rgba(255,255,255,0.08)",
      "--border-subtle": "rgba(255,255,255,0.04)",
      "--accent": "#10B981",
      "--accent-subtle": "rgba(16,185,129,0.15)",
      "--accent-text": "#FFFFFF",
      "--destructive": "#EF4444",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
    },
  },
  obsidian: {
    id: "obsidian", name: "Obsidian", mode: "dark",
    description: "Sleek minimal dark, violet",
    swatch: ["#0A0A0C", "#A855F7", "#EDEDF0"],
    vars: {
      "--background": "#0A0A0C",
      "--surface": "#16161A",
      "--surface-raised": "#1E1E24",
      "--surface-sunken": "#060608",
      "--text": "#EDEDF0",
      "--text-secondary": "#B8B8C0",
      "--text-muted": "#888892",
      "--border": "rgba(255,255,255,0.08)",
      "--border-subtle": "rgba(255,255,255,0.04)",
      "--accent": "#A855F7",
      "--accent-subtle": "rgba(168,85,247,0.15)",
      "--accent-text": "#FFFFFF",
      "--destructive": "#EF4444",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
    },
  },
  yuva: {
    id: "yuva", name: "Yuva", mode: "dark",
    description: "Bold vibrant dark, magenta",
    swatch: ["#150A22", "#D946EF", "#F7ECFF"],
    vars: {
      "--background": "#150A22",
      "--surface": "#20122F",
      "--surface-raised": "#2D1A40",
      "--surface-sunken": "#0E0618",
      "--text": "#F7ECFF",
      "--text-secondary": "#D4C0E0",
      "--text-muted": "#A88EC0",
      "--border": "rgba(255,255,255,0.08)",
      "--border-subtle": "rgba(255,255,255,0.04)",
      "--accent": "#D946EF",
      "--accent-subtle": "rgba(217,70,239,0.15)",
      "--accent-text": "#FFFFFF",
      "--destructive": "#EF4444",
      "--success": "#22C55E",
      "--warning": "#F59E0B",
    },
  },
  "hc-dark": {
    id: "hc-dark", name: "High Contrast Dark", mode: "dark",
    description: "Maximum contrast dark",
    swatch: ["#000000", "#FFFFFF", "#4DA6FF"],
    vars: {
      "--background": "#000000",
      "--surface": "#0A0A0A",
      "--surface-raised": "#1A1A1A",
      "--surface-sunken": "#000000",
      "--text": "#FFFFFF",
      "--text-secondary": "#E0E0E0",
      "--text-muted": "#CCCCCC",
      "--border": "#FFFFFF",
      "--border-subtle": "#888888",
      "--accent": "#4DA6FF",
      "--accent-subtle": "rgba(77,166,255,0.2)",
      "--accent-text": "#000000",
      "--destructive": "#FF4444",
      "--success": "#44FF44",
      "--warning": "#FFAA00",
    },
  },
};

export const lightPalettes = Object.values(palettes).filter(p => p.mode === "light");
export const darkPalettes = Object.values(palettes).filter(p => p.mode === "dark");

export function applyPalette(paletteId) {
  const p = palettes[paletteId];
  if (!p) return;
  const root = document.documentElement;
  root.setAttribute("data-theme", paletteId);
  Object.entries(p.vars).forEach(([k, v]) => root.style.setProperty(k, v));
}